listen_addr="*"
listen_port=4443
# TLS settings
use_proxy_protocol=false

# Broker API settings
ticket_api_url="https://127.0.0.1:8443/uds/rest/tunnelpq/ticket"
verify_ssl=true
broker_auth_token="
