#!/usr/bin/env python3
"""
Coffee Pie - Defrag translations.json

1. Collapses \\n and extra whitespace in Spanish (es) text so LibreTranslate
   gets clean paragraphs instead of fragmented lines.
2. Removes all non-Spanish translations (they were corrupted by fragmented input).
3. Merges duplicate keys that result from whitespace-only differences.
4. Adds merged-paragraph entries for WRichText components with multiple children,
   using __group__ prefix. These give LibreTranslate full paragraph context.

Usage:
    python3 scripts/defrag_translations.py [--merge-groups]
"""

import json, os, sys, time, re

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.join(SCRIPTS_DIR, '..', 'coffeepie_website')
TRANSLATIONS_PATH = os.path.join(PROJECT_DIR, 'public', 'translations.json')
BACKUP_DIR = os.path.join(PROJECT_DIR, 'public', 'translations_backups')

LANG_ES = 'es'
# All target languages that will be regenerated by translate.py
TARGET_LANGS = ['en', 'pt', 'fr', 'de', 'ja', 'ko', 'zh', 'ru', 'ar', 'hi']

os.makedirs(BACKUP_DIR, exist_ok=True)


def clean(text):
    """Collapse all whitespace into single spaces, trim."""
    if not text:
        return text
    return ' '.join(text.split())


# --- Groups from HTML analysis ---
# Each group: concatenated text of all children in a WRichText component
# Key = the concatenated Spanish text (joined with ' ||| ')
# The individual fragment keys are kept for lang.js matching
# The merged key is used by translate.py for contextual translation

PARAGRAPH_GROUPS = {
    # comp-lyegqis5__item1 (Hero slider body - 5 content paragraphs)
    'hero': [
        "Te imaginas poder aumentar el poder de cómputo y capacidad de tu equipo con un par de clicks y sin pagar de más?...",
        "Te imaginas no tener que tirar a la basura tu equipo cada 2 ó 3 años porque ya está lento, obsoleto, se te dañó un puerto o una tecla?...",
        "Te imaginas poder cambiar las partes de tu equipo sin tener que comprar uno nuevo cada que cambien tus necesidades?...",
        "Te imaginas poder contribuir al desarrollo social e industrial, pero sin afectar al medio ambiente dejando de generar basura electrónica?...",
        "Con Coffee Pie® ahora todo eso es posible!",
    ],
    # Add more groups here as needed:
    # 'about-body': ["Fragment 1", "Fragment 2", ...],
}


def main():
    merge_groups = '--merge-groups' in sys.argv

    # Backup
    ts = time.strftime('%Y%m%d_%H%M%S')
    backup_path = os.path.join(BACKUP_DIR, f'translations_pre_defrag_{ts}.json')
    with open(TRANSLATIONS_PATH, 'r', encoding='utf-8') as f:
        original_content = f.read()
    with open(backup_path, 'w', encoding='utf-8') as f:
        f.write(original_content)
    print(f'[backup] Saved to {backup_path}')

    data = json.loads(original_content)
    total_before = len(data)
    print(f'[load] {total_before} entries')

    # Step 1: Clean Spanish text, remove corrupted translations, rebuild
    new_data = {}
    cleansed = 0
    deduped = 0
    removed_translations = 0

    for old_key, entry in data.items():
        if not isinstance(entry, dict):
            new_data[old_key] = entry
            continue

        es_raw = entry.get(LANG_ES, '')
        es_clean = clean(es_raw)

        if not es_clean or len(es_clean) < 2:
            new_data[old_key] = entry
            continue

        if es_clean != es_raw:
            cleansed += 1

        new_entry = {LANG_ES: es_clean}

        # Remove all non-Spanish translations (corrupted)
        for lang in entry:
            if lang != LANG_ES:
                removed_translations += 1

        # Use cleaned Spanish as key
        new_key = es_clean

        if new_key in new_data:
            deduped += 1
        else:
            new_data[new_key] = new_entry

    total_after_step1 = len(new_data)

    # Step 2: Add merged paragraph groups if requested
    groups_added = 0
    if merge_groups:
        for group_name, fragments in PARAGRAPH_GROUPS.items():
            merged_key = '__group__' + group_name
            merged_es = ' ||| '.join(fragments)
            merged_entry = {LANG_ES: merged_es}
            if merged_key not in new_data:
                new_data[merged_key] = merged_entry
                groups_added += 1
            # Also ensure each fragment exists as individual key
            for frag in fragments:
                frag_clean = clean(frag)
                if frag_clean not in new_data:
                    new_data[frag_clean] = {LANG_ES: frag_clean}

    # Save
    total_final = len(new_data)
    print(f'[clean] {cleansed} entries had whitespace collapsed')
    print(f'[merge] {deduped} duplicate keys merged')
    print(f'[translations] {removed_translations} corrupted translations removed')
    if merge_groups and groups_added:
        print(f'[groups] {groups_added} merged paragraph groups added')
    print(f'[result] {total_before} -> {total_after_step1} entries after defrag')
    if groups_added:
        print(f'[result] + {groups_added} group entries = {total_final} total')

    tmp_path = TRANSLATIONS_PATH + '.tmp'
    with open(tmp_path, 'w', encoding='utf-8') as f:
        json.dump(new_data, f, ensure_ascii=False, indent=4)
    os.replace(tmp_path, TRANSLATIONS_PATH)

    # Validate
    with open(TRANSLATIONS_PATH, 'r', encoding='utf-8') as f:
        json.load(f)
    print('[validate] JSON is valid')

    # Stats on empty translations
    with_es = sum(1 for k, v in new_data.items() if isinstance(v, dict) and LANG_ES in v and v[LANG_ES].strip())
    missing_all = sum(1 for k, v in new_data.items()
                      if isinstance(v, dict) and LANG_ES in v and v[LANG_ES].strip()
                      and all(lang not in v or not v[lang] for lang in TARGET_LANGS))
    print(f'[status] {with_es} entries with Spanish text')
    print(f'[status] {missing_all} entries need translation (no target language translations)')

    print('\nDone. Run: python3 scripts/translate.py  to get fresh translations.')


if __name__ == '__main__':
    main()
