project-includes = [
    "src/**/*.py*",
    "src/**/*.ipynb",
]

# Exclude scripts from transports transports/*/scripts/*
project-excludes = [
    "src/**/transports/**/scripts/**/*.py",
    "src/uds/core/util/ldaputil_old.py",
]

python-platform = "linux"

