FROM rust:1.85-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config libssl-dev \
    && rm -rf /var/lib/apt/lists/*

COPY . .

EXPOSE 43910
CMD ["cargo", "run", "--release"]
